# permissions for end users to view mapdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mapdata-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: mapdata-viewer-role
rules:
- apiGroups:
  - infra.shpboris
  resources:
  - mapdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.shpboris
  resources:
  - mapdata/status
  verbs:
  - get
