---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infra.shpboris
  resources:
  - mapdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.shpboris
  resources:
  - mapdata/finalizers
  verbs:
  - update
- apiGroups:
  - infra.shpboris
  resources:
  - mapdata/status
  verbs:
  - get
  - patch
  - update
